-- Domains and Types
CREATE DOMAIN dom_name VARCHAR(64);
CREATE DOMAIN dom_email VARCHAR(64);
CREATE DOMAIN dom_dni VARCHAR(16);
CREATE DOMAIN dom_agency_rif VARCHAR(32);
CREATE DOMAIN dom_phone_number VARCHAR(16);
CREATE DOMAIN dom_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
CREATE DOMAIN dom_reservation_time AS INTEGER
  CHECK (VALUE BETWEEN 1 AND 7);
CREATE DOMAIN dom_payments_quantity AS INTEGER
  CHECK (VALUE BETWEEN 1 AND 2);
CREATE DOMAIN dom_discount_percentage AS INTEGER
  CHECK (VALUE BETWEEN 0 AND 100);
CREATE TYPE type_payment_method AS ENUM ('E', 'D', 'T', 'TD', 'TC');
